import { type Beer } from "@/types";

export const BOARD_DIMENSION = 3;

export const LIST_EXTRA_BEERS = 3;
// We add extra beers to the list that are not on the board
// to decrease the chance of a bingo

export const BOARD_TILES = BOARD_DIMENSION ** 2;

export const HARRY_CHOICE_QUOTA = 5;
// how many of harry's choices should be required
// in each board

export const BEERS: Beer[] = [
	{
		"id": 1,
		"section": 1,
		"name": "HONEY GUM",
		"flavour": "CARAMEL AND RED GUM HONEY IPA",
		"company": "CLIFTON HILL BREWING",
		"state": "VIC",
	},
	{
		"id": 2,
		"section": 1,
		"name": "CHOC A L'ORANGE",
		"flavour": "ORANGE CHOCOLATE STOUT",
		"company": "BREWMANITY BEER CO",
		"state": "VIC",
	},
	{
		"id": 3,
		"section": 1,
		"name": "SPAGHETTI SAISON",
		"flavour": "SPAGHETTI ALE",
		"company": "SIX STRING BREWING CO",
		"state": "NSW",
	},
	{
		"id": 4,
		"section": 1,
		"name": "COCOA COMET",
		"flavour": "HOT CHOCOLATE PORTER",
		"company": "THE BREW BARON BEER CO",
		"state": "QLD",
	},
	{
		"id": 5,
		"section": 1,
		"name": "IMPERIAL COOKIE STOUT",
		"flavour": "NUTTY CRUMB COOKIE STOUT",
		"company": "WIRED CRUMBS",
		"state": "NZ",
	},
	{
		"id": 6,
		"section": 1,
		"name": "UNLIKELY FRIENDS",
		"flavour": "MATCHA AND WHITE CHOCOLATE STOUT",
		"company": "AETHEON BREWING",
		"state": "WA",
	},
	{
		"id": 7,
		"section": 1,
		"name": "WHITE FOREST",
		"flavour": "CHERRY AND WHITE CHOCOLATE ALE",
		"company": "RED DUCK",
		"state": "VIC",
	},
	{
		"id": 8,
		"section": 1,
		"name": "DANK AND STORMY",
		"flavour": "HOPS AND GINGER AMBER ALE",
		"company": "AKASHA BREWING CO",
		"state": "NSW",
	},
	{
		"id": 9,
		"section": 1,
		"name": "SCREAMIN' PEACH",
		"flavour": "PEACH AND CHILLIS",
		"company": "CANOBOLAS BREWING CO",
		"state": "NSW",
	},
	{
		"id": 10,
		"section": 1,
		"name": "FUNKY GOSE TO HOLLYWOOD",
		"flavour": "BLACKBERRY GOSE SOUR",
		"company": "WANDANA BREWING CO",
		"state": "NSW",
	},
	{
		"id": 11,
		"section": 1,
		"name": "OLD MATE",
		"flavour": "TOFFEE, VANILLA, AND ORANGE AMBER ALE",
		"company": "JETTY ROAD BREWERY",
		"state": "VIC",
	},
	{
		"id": 12,
		"section": 1,
		"name": "KING RIVER DOUBLE RED IPA",
		"flavour": "PASSIONFRUIT, GRAPEFRUIT, AND CITRUS RED IPA",
		"company": "KING RIVER BREWING",
		"state": "VIC",
	},
	{
		"id": 13,
		"section": 1,
		"name": "DON'T TAKE THE PITH",
		"flavour": "CHOCOLATE AND ORANGE PORTER",
		"company": "HIKER BREWING CO",
		"state": "QLD",
	},
	{
		"id": 14,
		"section": 1,
		"name": "BRUNSWICK GRAPE ALE",
		"flavour": "SHIRAZ GRAPE ALE",
		"company": "TEMPLE BREWING CO",
		"state": "VIC",
	},
	{
		"id": 15,
		"section": 1,
		"name": "PEPPER, PEPPER, PEPPER",
		"flavour": "CHILLI PEPPER, BLACK PEPPER, AND SZECHUAN PEPPER IPA",
		"company": "MOLLY ROSE BREWING",
		"state": "VIC",
	},
	{
		"id": 16,
		"section": 1,
		"name": "DOUBLE-LEMON SHOCHU CANDY",
		"flavour": "LEMON SHOCHU PALE LAGER",
		"company": "STOMPING GROUND BREWING CO",
		"state": "VIC",
	},
	{
		"id": 17,
		"section": 1,
		"name": "SMOKE RINGS",
		"flavour": "PINEAPPLE AND CHERRY KETTLE SOUR",
		"company": "CAVALIER BREWING",
		"state": "VIC",
	},
	{
		"id": 18,
		"section": 1,
		"name": "HYBRID THEORY RED RYE IPA",
		"flavour": "RED MALTS HOPPY IPA",
		"company": "RUSTY PENNY BREWING",
		"state": "NSW",
	},
	{
		"id": 19,
		"section": 1,
		"name": "OPEN RELATIONSHIP",
		"flavour": "MALT AND HOPS PILSNER LAGER",
		"company": "DEVILBEND FARM BEER CO",
		"state": "VIC",
	},
	{
		"id": 20,
		"section": 1,
		"name": "KRUSHBERRY PI 3.14%",
		"flavour": "VANILLA BERRY PIE SOUR",
		"company": "KAIJU! BEER",
		"state": "VIC",
	},
	{
		"id": 21,
		"section": 2,
		"name": "BOUNTY HUNTER",
		"flavour": "COCONUT AND CACAO RUM STOUT",
		"company": "SEEKER BREWING",
		"state": "NSW",
	},
	{
		"id": 22,
		"section": 2,
		"name": "HIGH CARB WHITE IPA",
		"flavour": "FRUITY SPICY HIGH CARB IPA",
		"company": "GRIFFINS BREWING",
		"state": "NSW",
	},
	{
		"id": 23,
		"section": 2,
		"name": "TARTE NOIR",
		"flavour": "MULBERRY AND VANILLA PASTRY KETTLE SOUR",
		"company": "PRECINCT BREWING",
		"state": "QLD",
	},
	{
		"id": 24,
		"section": 2,
		"name": "PARADISE PILS",
		"flavour":
			"NO FUCKING CLUE. DOES NOT SPECIFY. UNMODDED MALT AND LONG FERMENTATION PILSNER LAGER",
		"company": "FRESHWATER BREWING CO",
		"state": "NSW",
	},
	{
		"id": 25,
		"section": 2,
		"name": "RUM RUNNING",
		"flavour": "PINEAPPLE AND NEIPA RUM RUNNER COCKTAIL BEER",
		"company": "SMILEY BREWING",
		"state": "VIC",
	},
	{
		"id": 26,
		"section": 2,
		"name": "NITRO CITRUS BLOOD ORANGE CHOCOLATE PORTER",
		"flavour": "",
		"company": "BLACKFLAG BREWERY",
		"state": "QLD",
	},
	{
		"id": 27,
		"section": 2,
		"name": "YU ZERIOUS? YUZU RUSS",
		"flavour": "YUZU AND SHANDY",
		"company": "URBAN ALLEY BREWERY",
		"state": "VIC",
	},
	{
		"id": 28,
		"section": 2,
		"name": "DUBBEL DUTCH",
		"flavour": "BISCUIT AND SPICE BELGIAN DUBBEL",
		"company": "HOP HEN BREWING",
		"state": "VIC",
	},
	{
		"id": 29,
		"section": 2,
		"name": "SOOLONG SUCKA",
		"flavour": "OOLONG AND BLACK TEA FRUITY IPA",
		"company": "BOWDEN BREWING CO",
		"state": "SA",
	},
	{
		"id": 30,
		"section": 2,
		"name": "WISE AND THE FOOLISH",
		"flavour": "CARAMEL, MALT, BANANA AND SPICE WEIZENBOCK",
		"company": "CAPTAIN BLIGH'S BREWERY",
		"state": "TAS",
	},
	{
		"id": 31,
		"section": 2,
		"name": "GUAVA LAVA IMPERIAL IPL",
		"flavour": "GUAVA AND INDIA PALE LAGER",
		"company": "7TH DAY BREWERY",
		"state": "NSW",
	},
	{
		"id": 32,
		"section": 2,
		"name": "PIG PICKIN' CAKE",
		"flavour": "CITRUS VANILLA MILKSHAKE IPA",
		"company": "OCEAN REACH BREWING",
		"state": "VIC",
	},
	{
		"id": 33,
		"section": 2,
		"name": "HOPLESS BOTANICAL IPA",
		"flavour": "HOREHOUND, ELDERBERRY AND HONEY GRUIT IPA",
		"company": "SAUCE BREWING CO",
		"state": "NSW",
	},
	{
		"id": 34,
		"section": 2,
		"name": "WAKAME UP BEFORE YOU GOSE",
		"flavour": "KETTLE SOUR…SUSHI?",
		"company": "TWOBAYS BREWING CO",
		"state": "VIC",
	},
	{
		"id": 35,
		"section": 2,
		"name": "MICHELAGER",
		"flavour": "MEXICAN TOMATO LIME CHILLI LAGER",
		"company": "BLACK HOPS BREWING",
		"state": "QLD",
	},
	{
		"id": 36,
		"section": 2,
		"name": "SMOOTH CAFFEINATOR",
		"flavour": "CARAMEL AFFOGATO STOUT",
		"company": "KING TIDE BREWING",
		"state": "NSW",
	},
	{
		"id": 37,
		"section": 2,
		"name": "BLACKBERRIES, BLUEBERRIES, AND SOUR PATCH KIDS!",
		"flavour": "FRUITY SOUR PATCH KETTLE SOUR",
		"company": "BOBS BEER",
		"state": "QLD",
	},
	{
		"id": 38,
		"section": 2,
		"name": "SUPERMASSIVE BLACK HOLE",
		"flavour": "COCOA AND ALMOND PASTRY STOUT",
		"company": "DEEDS BREWING",
		"state": "VIC",
	},
	{
		"id": 39,
		"section": 2,
		"name": 'FEILADH MOR ("GREAT KILT")',
		"flavour": "RICH PEATY SCOTCH ALE",
		"company": "BADLANDS BREWERY",
		"state": "NSW",
	},
	{
		"id": 40,
		"section": 2,
		"name": "MAI TAIPA",
		"flavour": "MAI TAI STYLE BEER",
		"company": "WAYWARD BREWING CO",
		"state": "NSW",
	},
	{
		"id": 41,
		"section": 3,
		"name": "HAZE TRAIN",
		"flavour": "CITRUS TROPICAL HAZY IPA",
		"company": "SHELTER BREWING CO",
		"state": "WA",
	},
	{
		"id": 42,
		"section": 3,
		"name": "CREATURE OF THE DEEP",
		"flavour": "CHOCOLATE AND KELP OATMEAL STOUT",
		"company": "AETHER BREWING",
		"state": "QLD",
	},
	{
		"id": 43,
		"section": 3,
		"name": "TRIPLE STICKY",
		"flavour": "HOPPY LAGER",
		"company": "FORREST BREWING CO",
		"state": "VIC",
	},
	{
		"id": 44,
		"section": 3,
		"name": "ROSE PETAL RASPBERRY SOUR",
		"flavour": "RASPBERRY AND ROSE PETAL PINK SOUR",
		"company": "BROULEE BREWHOUSE",
		"state": "NSW",
	},
	{
		"id": 45,
		"section": 3,
		"name": "SHINIGAMI - UMAMI SMOKED PORTER",
		"flavour": "DARK CHOCOLATE, DASHI AND TAMARI SMOKED BEER",
		"company": "POWDER MONKEY AUSTRALIA",
		"state": "NSW",
	},
	{
		"id": 46,
		"section": 3,
		"name": "SUCKER PUNCH STRAWBERRIES AND CREAM LOLLIPOP SOUR",
		"flavour": "MARSHMALLOW AND STRAWBERRY PASTRY SOUR",
		"company": "WORKING TITLE BREW CO",
		"state": "QLD",
	},
	{
		"id": 47,
		"section": 3,
		"name": "AURORA AUSTRALIS WONDER ALE",
		"flavour": "DARK RED BELGIAN ALE",
		"company": "FRENCHIES BREWERY",
		"state": "NSW",
	},
	{
		"id": 48,
		"section": 3,
		"name": "LAZY BONES",
		"flavour": "PEACH, LIME, AND CITRUS",
		"company": "VALLEY HOPS BREWING",
		"state": "QLD",
	},
	{
		"id": 49,
		"section": 3,
		"name": "PANDAN WHITE CHOCOLATE STOUT",
		"flavour": "PANDAN, CHOCOLATE, AND COFFEE PASTRY STOUT",
		"company": "ROCKS BREWING CO",
		"state": "NSW",
	},
	{
		"id": 50,
		"section": 3,
		"name": "SPARKLING SAISON NOIR",
		"flavour": "SPICE, HOPS, AND CHERRIES SAISON ALE",
		"company": "BEERERATNE BREWING",
		"state": "VIC",
	},
	{
		"id": 51,
		"section": 3,
		"name": "HOP YEARNING",
		"flavour": "GRAPEFRUIT, STONE FRUIT, AND PINE AMERICAN IPA",
		"company": "WESTSIDE ALE WORKS",
		"state": "VIC",
	},
	{
		"id": 52,
		"section": 3,
		"name": "PINEAPPLE PUNCH",
		"flavour": "PINAPPLE AND COCONUT",
		"company": "COMMON GROUND BREWING",
		"state": "QLD",
	},
	{
		"id": 53,
		"section": 3,
		"name": "TWO THUMBS TOASTED IRONBARK WEST COAST IPA",
		"flavour": "CITRUS, PINE, AND EUCALYPTUS AMERICAN IPA",
		"company": "NEWSTEAD BREWING CO",
		"state": "QLD",
	},
	{
		"id": 54,
		"section": 3,
		"name": "LEMON AND KEY LIME MERINGUE PIE SOUR",
		"flavour": "LEMON, KEY LIME, AND MERINGUE KETTLE SOUR",
		"company": "GOOD FOLK BREWING",
		"state": "NSW",
	},
	{
		"id": 55,
		"section": 3,
		"name": "ANGRY FISH",
		"flavour": "DARK BERRY MALT BALTIC PORTER",
		"company": "NOISY MINOR",
		"state": "QLD",
	},
	{
		"id": 56,
		"section": 3,
		"name": "THE SANGA",
		"flavour": "PEANUT BUTTER AND JELLY…SANDWICH BEER?",
		"company": "SOAPBOX BEER",
		"state": "QLD",
	},
	{
		"id": 57,
		"section": 3,
		"name": "HONEY, HONEY, JOY, JOY",
		"flavour": "HONEY CORN FLAKES",
		"company": "RAMBLERS ALE WORKS",
		"state": "VIC",
	},
	{
		"id": 58,
		"section": 3,
		"name": "PICK OF THE BUNCH",
		"flavour": "BANANA CREAM PIE",
		"company": "SLIPSTREAM BREWING CO",
		"state": "QLD",
	},
	{
		"id": 59,
		"section": 3,
		"name": "BLACK FOREST ESPRESSO",
		"flavour": "CHOCOLATE, COFFEE, VANILLA, AND CHERRIES PASTRY STOUT",
		"company": "THE MILL BREWERY",
		"state": "VIC",
	},
	{
		"id": 60,
		"section": 3,
		"name": "BRAUPAKT",
		"flavour": "SPICY, FRUITY, AND YEASTY BITCH!",
		"company": "WEIHENSTEPHAN",
		"state": "GER",
	},
	{
		"id": 61,
		"section": 4,
		"name": "THE COWBOY SLICKSHAKE",
		"flavour": "CHOC, BUTTERSCOTCH PASTRY STOUT",
		"company": "GOOD LAND BREWING CO",
		"state": "VIC",
	},
	{
		"id": 62,
		"section": 4,
		"name": "???",
		"flavour": "???",
		"company": "???",
		"state": "???",
	},
	{
		"id": 63,
		"section": 4,
		"name": "VANTA MANTA",
		"flavour": "DARK LAGER SCHWARZBIER",
		"company": "STRADDIE BREWING CO",
		"state": "QLD",
	},
	{
		"id": 64,
		"section": 4,
		"name": "SLICE OF HEAVEN",
		"flavour": "PASSIONFRUIT AND BLACKCURRENT PILSNER",
		"company": "DAD AND DAVE'S BREWING",
		"state": "NSW",
	},
	{
		"id": 65,
		"section": 4,
		"name": "SOUTHERN CROSSED LOVERS",
		"flavour": "STONE FRUIT, PASSIONFRUIT, AND PINEAPPLE HAZY IPA",
		"company": "SHOUT BREWING CO",
		"state": "NSW",
	},
	{
		"id": 66,
		"section": 4,
		"name": "MR. PHANTASTIC",
		"flavour": "GUAVA, PASSIONFRUIT, AND CRUSHED GOOSEBERRY COLD IPA",
		"company": "DANGEROUS ALES",
		"state": "NSW",
	},
	{
		"id": 67,
		"section": 4,
		"name": "SPI-SKI MARGARITA GOSE",
		"flavour": "SPICY MARGARITA GOSE SOUR",
		"company": "MOUNTAIN GOAT BEER",
		"state": "VIC",
	},
	{
		"id": 68,
		"section": 4,
		"name": "DDH UNICORN FRAPPE NEIPA",
		"flavour": "FUCKLOADS OF FRUIT, SOME LACTOSE AND VANILLA, MILKSHAKE IPA",
		"company": "GREEN BEACON",
		"state": "QLD",
	},
	{
		"id": 69,
		"section": 4,
		"name": "SLATTERPUS WATERMELON SOUR",
		"flavour": "WATERMELON AND HIBISCUS KETTLE SOURED BEER",
		"company": "COPPERLODE BREWING CO",
		"state": "QLD",
	},
	{
		"id": 70,
		"section": 4,
		"name": "DAILY TOT' - RUM RAISIN BROWN ALE",
		"flavour": "RAISIN, OAK, AND SPICED RUM UK BROWN ALE",
		"company": "BOATROCKER BREWERS AND DISTILLERS",
		"state": "VIC",
	},
	{
		"id": 71,
		"section": 4,
		"name": "FANTASTIC SOUR",
		"flavour": "FANTA STYLE KETTLE SOUR",
		"company": "REVEL BREWING CO",
		"state": "QLD",
	},
	{
		"id": 72,
		"section": 4,
		"name": "VANILLA BEAN PANNA COTTA",
		"flavour": "CARAMEL, TOFFEE, VANILLA, MALT WHITE STOUT",
		"company": "YOUR MATES BREWING CO",
		"state": "QLD",
	},
	{
		"id": 73,
		"section": 4,
		"name": "ALTERNATE BIER",
		"flavour": "NO FUCKING CLUE. DOES NOT SPECIFY. HOPPY MALTY ALTBIER?",
		"company": "BUCKET BREWERY",
		"state": "NSW",
	},
	{
		"id": 74,
		"section": 4,
		"name": "DOUBLE BOOTI KNEIPA",
		"flavour": "NO FUCKING CLUE. DOES NOT SPECIFY. NEIPA DOUBLE",
		"company": "THE COASTAL BREWING COMPANY",
		"state": "NSW",
	},
	{
		"id": 75,
		"section": 4,
		"name": "OORAY FOR GILBERT",
		"flavour": "OORAY PLUM, DARK MID. ",
		"company": "THE SOCIAL BREWERS",
		"state": "NSW",
	},
	{
		"id": 76,
		"section": 4,
		"name": "THICKER THAN WATER",
		"flavour": "BRAZILIAN BLOOD LIMEAIDE PASTRY SOUR",
		"company": "NOODLEDOOF",
		"state": "VIC",
	},
	{
		"id": 77,
		"section": 4,
		"name": "INSANE KOLCHE POSSE",
		"flavour": "CITRUSY, BUILT LIKE A WEST COAST IPA. FERMENTED LIKE A KOLCHE.",
		"company": "PSYCHO SUZIES BREWING",
		"state": "QLD",
	},
	{
		"id": 78,
		"section": 4,
		"name": "BISCOFF CHOCOLATE BROWNIE PORTER",
		"flavour": "BISCOFF, CHOCOLATE, AND BISCUIT PORTER.",
		"company": "BAD SHEPARD BREWING CO",
		"state": "VIC",
	},
	{
		"id": 79,
		"section": 4,
		"name": "BILLSON'S FLAVOURED SOUR BEER",
		"flavour": "NO FUCKING CLUE. DOES NOT SPECIFY. BREWING FOR A LONG TIME.",
		"company": "BILLSON'S BREWERY",
		"state": "VIC",
	},
	{
		"id": 80,
		"section": 4,
		"name": "GOLDEN ROOTS",
		"flavour": "SPICED VOLCANIC SWEET POTATO COPPER ALE",
		"company": "EARTH BEER COMPANY",
		"state": "NSW",
	},
	{
		"id": 81,
		"section": 5,
		"name": "SMOKED KELP STOUT",
		"flavour": "PEAT SMOKED KELP IMPERIAL STOUT",
		"company": "MORRISON BREWERY",
		"state": "TAS",
	},
	{
		"id": 82,
		"section": 5,
		"name": "THE 'H' IS SILENT",
		"flavour": "CHARDONNAY CO FERMENTED SOUR. KATH AND KIM TRIBUTE.",
		"company": "RECKLESS BREWING CO",
		"state": "NSW",
	},
	{
		"id": 83,
		"section": 5,
		"name": "WEST COAST STORY",
		"flavour": "TROPICAL AND STONE FRUIT AUSTRALIAN IPA",
		"company": "PRICKLY PETE AND THE WOLF BREWING CO",
		"state": "NSW",
	},
	{
		"id": 84,
		"section": 5,
		"name": "SIMZ SPICY VANILLA GORILLA",
		"flavour": "VANILLA AND CHERRY SOUR BARREL AGED ",
		"company": "DOLLAR BILL BREWING",
		"state": "VIC",
	},
	{
		"id": 85,
		"section": 5,
		"name": "THE TERPINATOR",
		"flavour": "WEED, CITRUS, AND HOPS? BONGWATER WITH A BERRY PUMP.",
		"company": "WOLF OF THE WILLOWS",
		"state": "VIC",
	},
	{
		"id": 86,
		"section": 5,
		"name": "TRADIES BREAKFAST",
		"flavour": "VIENNA COFFEE LAGER MEETS CUSTARD TART",
		"company": "THE SUBURBAN BREW",
		"state": "SA",
	},
	{
		"id": 87,
		"section": 5,
		"name": "ABOMINABLE S'MORES",
		"flavour": "CHOCOLATE, VANILLA, BISCUITS, MARSHMALLOW",
		"company": "BRIGHT BREWERY",
		"state": "VIC",
	},
	{
		"id": 88,
		"section": 5,
		"name":
			"BANANA AND BLUEBERRY IMPERIAL MAPLE MACCADAMIA PANCAKE SMOOTHIE SOUR",
		"flavour":
			"SELF DESCRIBED AS AN ABOMINATION OF A BEER. SEVERAL ALLERGY WARNINGS.",
		"company": "SEVEN MILE BREWING CO",
		"state": "NSW",
	},
	{
		"id": 89,
		"section": 5,
		"name": "APFELSTRUDLE PASTRY HEFE",
		"flavour": "APPLE, VANILLA, SPICE HEFEWEIZEN",
		"company": "MISMATCH BREWING CO",
		"state": "SA",
	},
	{
		"id": 90,
		"section": 5,
		"name": "ROCKY ROAD CAMPFIRE CHOCOLATE SMOKED STOUT",
		"flavour": "MARSHMALLOW, CHOCOLATE, AND COCONUT SMOKED PORTER",
		"company": "BLACKMAN'S",
		"state": "VIC",
	},
	{
		"id": 91,
		"section": 5,
		"name": "SWEET AS PIE",
		"flavour": "APPLE PIE BISCUIT ALE. QUOTES JEFF GOLDBLUM IN DESCRIPTION.",
		"company": "FUTURE MAGIC BREWING CO",
		"state": "QLD",
	},
	{
		"id": 92,
		"section": 5,
		"name": "SAB BITTER",
		"flavour": "MALTS, GOLDING, AND HOPS. EXTRA SPECIAL BITTER.",
		"company": "ST ANDREWS BEACH BREWERY",
		"state": "VIC",
	},
	{
		"id": 93,
		"section": 5,
		"name": "SMOOTH LANDING",
		"flavour": "FRUIT PUNCH HAZY IPA",
		"company": "MOUNTAIN CULTURE",
		"state": "NSW",
	},
	{
		"id": 94,
		"section": 5,
		"name": "PARTICAL FUSION - WORLDS COLLIDE",
		"flavour": "WINE, FLORAL AND CITRUS",
		"company": "THREE TAILS BREWING",
		"state": "NSW",
	},
	{
		"id": 95,
		"section": 5,
		"name": "ZOMBIE IMPERIAL SOUR",
		"flavour": "TIKI ZOMBIE COCKTAIL STYLE TROPICAL KETTLE SOUR",
		"company": "BATCH BREWING COMPANY",
		"state": "NSW",
	},
	{
		"id": 96,
		"section": 5,
		"name": "EQUINOX '24",
		"flavour": "ORANGE ZEST BLOOD ORANGE CITRUS IMPERIAL IPA",
		"company": "HEROES AND VILLAINS",
		"state": "WA",
	},
	{
		"id": 97,
		"section": 5,
		"name": "HOLY SMOKES!",
		"flavour": "CAMEL SHIT. NOT FUCKING KIDDING. VIBES OF WHISKEY, APPARENTLY.",
		"company": "ROBE TOWN BREWERY",
		"state": "SA",
	},
	{
		"id": 98,
		"section": 5,
		"name": "SALVAGED CHERRY COLA",
		"flavour": "CHERRY COLA SPECIALTY BEER",
		"company": "CAPITAL BREWING CO",
		"state": "ACT",
	},
	{
		"id": 99,
		"section": 5,
		"name": "ESCAPE THE HEAT",
		"flavour": "JALAPENO BELGIAN SPECIALTY ALE",
		"company": "ESCAPE BREWING",
		"state": "VIC",
	},
	{
		"id": 100,
		"section": 5,
		"name": "MISO MACADAMIA STOUT",
		"flavour": "MACADAMIA AND WHITE MISO PORTER STOUT",
		"company": "4 HEARTS BREWING",
		"state": "QLD",
	},
	{
		"id": 101,
		"section": 6,
		"name": "STRAWBERRY CHAMPAGNE BEER",
		"flavour": "STRAWBERRIES AND WHITE WINE",
		"company": "LADY BURRA BREWHOUSE",
		"state": "SA",
	},
	{
		"id": 102,
		"section": 6,
		"name": "TRY AND BANH MI",
		"flavour": "COFFEE, DARK CHOCOLATE, NUTS, AND BISCUITY STOUT.",
		"company": "BREW DOG",
		"state": "QLD",
	},
	{
		"id": 103,
		"section": 6,
		"name": "???",
		"flavour": "CLASSIC PILSNER LAGER",
		"company": "WILLIE THE BOATMAN",
		"state": "NSW",
	},
	{
		"id": 104,
		"section": 6,
		"name": "CEREAL FOR DINNER",
		"flavour": "OAT CREAM CEREAL NEIPA",
		"company": "MODUS",
		"state": "NSW",
	},
	{
		"id": 105,
		"section": 6,
		"name": "BLACK MAMBA",
		"flavour": "BANANA, ESPRESSO, AND SPICE BLACK SAISON",
		"company": "IMPI BREWERS",
		"state": "WA",
	},
	{
		"id": 106,
		"section": 6,
		"name": "GRAND SLAM",
		"flavour": "STRAWBERRIES AND CREAM IMPERIAL KETTLE SOUR",
		"company": "LOCAL BREWING CO",
		"state": "VIC",
	},
	{
		"id": 107,
		"section": 6,
		"name": "BIG FEELINGS",
		"flavour": "YUZU, SEA SALT, CITRUS HAZY IPA",
		"company": "GARAGE PROJECT",
		"state": "NZ",
	},
	{
		"id": 108,
		"section": 6,
		"name": "THE NOTORIOUS F.I.G.",
		"flavour":
			"CARAMELISED FIG, HAZELNUT, TOFFEE, AND STICKY DATE UK BROWN ALE",
		"company": "MOFFAT BEACH BREWING CO",
		"state": "QLD",
	},
	{
		"id": 109,
		"section": 6,
		"name": "FLAT WHITE OATMEAL STOUT",
		"flavour": "ESPRESSO OATMEAL STOUT",
		"company": "WARRANDYTE BREWING CO",
		"state": "VIC",
	},
	{
		"id": 110,
		"section": 6,
		"name": "HELLHOUND",
		"flavour": "RAISIN, TOFFEE, TOBACCO, LEATHER, OAK, VANILLA BALTIC PORTER.",
		"company": "ON POINT BREWERY",
		"state": "VIC",
	},
	{
		"id": 111,
		"section": 6,
		"name": "LORD BARISTA",
		"flavour": "COFFEE AND MACADAMIA IMPERIAL STOUT",
		"company": "10 TOES BREWING",
		"state": "QLD",
	},
	{
		"id": 112,
		"section": 6,
		"name": "BACON ME CRAZY",
		"flavour": "BACON, CITRUS, SPICE AMERICAN IPA",
		"company": "STOIC BREWING",
		"state": "NSW",
	},
	{
		"id": 113,
		"section": 6,
		"name": "BEER-RIA TACO LAGER",
		"flavour": "TACO FLAVOURED FAUCHBIER",
		"company": "THE ZYTHOLOGIST",
		"state": "VIC",
	},
	{
		"id": 114,
		"section": 6,
		"name": "A BOY NAMED TIRAMISU",
		"flavour": "COFFEE, CHOCOLATE, SWEET PASTRY STOUT",
		"company": "CO-CONSPIRATORS BREWING",
		"state": "VIC",
	},
	{
		"id": 115,
		"section": 6,
		"name": "RASPBERRY SHERBET BOMB",
		"flavour": "RASPBERRY, DAISY, SHERBET SPECIALTY BEER",
		"company": "MOON DOG",
		"state": "VIC",
	},
	{
		"id": 116,
		"section": 6,
		"name": "GINGER MONKEY",
		"flavour": "GINGER, VANILLA, SPICED OAK, HINTS OF ORANGE, COCKTAIL.",
		"company": "MONKEY SHOULDER",
		"state": "SCOTLAND",
	},
	{
		"id": 117,
		"section": 6,
		"name": "MATSO'S PINA COLADA",
		"flavour": "EXACTLY AS IT SAYS. COCONUT, PINEAPPLE, AND RUM.",
		"company": "MATSO",
		"state": "???",
	},
	{
		"id": 118,
		"section": 6,
		"name": "EDDIES CRISP APPLE",
		"flavour": "APPLE AND SPICE TRADITIONAL CIDER",
		"company": "EDDIES CIDER",
		"state": "VIC",
	},
	{
		"id": 119,
		"section": 6,
		"name": "CLOUDY APPLE AND GINGER",
		"flavour": "APPLE AND GINGER CIDER",
		"company": "SPREYTON CIDER CO",
		"state": "TAS",
	},
	{
		"id": 120,
		"section": 6,
		"name": "???",
		"flavour": "???",
		"company": "???",
		"state": "???",
	},
];
