import { type Beer } from "@/types";

export const PADDLE_SIZE = 5;

export const BOARD_DIMENSION = 3;

export const LIST_EXTRA_BEERS = 3;
// We add extra beers to the list that are not on the board
// to decrease the chance of a bingo

export const BOARD_TILES = BOARD_DIMENSION ** 2;

export const BEER_LIST_SIZE = BOARD_TILES + LIST_EXTRA_BEERS;

export const HARRY_CHOICE_QUOTA = 5;
// how many of harry's choices should be required
// in each board

export const BEERS: Beer[] = [
	{
		id: 1,
		section: 1,
		flavour: "Cream Ale",
		name: "sippin' soda",
		company: "smiley brewing co",
		abv: 5,
	},
	{
		id: 2,
		section: 1,
		flavour: "IPA - Red",
		name: "Breakfast Red IPA",
		company: "aether brewing",
		abv: 6.5,
	},
	{
		id: 3,
		section: 1,
		flavour: "Lager - Classic Pilsner",
		name: "Chilli Pilli",
		company: "2 halfs brewing distilling",
		abv: 5,
	},
	{
		id: 4,
		section: 1,
		flavour: "Sour - Berliner Weisse",
		name: "El Frambueso Tequila Sour",
		company: "brewmanity beer co",
		abv: 4.5,
	},
	{
		id: 5,
		section: 1,
		flavour: "Bourbon Barrel Aged Imperial Stout",
		name: "Master of Shadows",
		company: "fox Friday",
		abv: 11,
	},
	{
		id: 6,
		section: 1,
		flavour: "Sour - Smoothie",
		name: "Rainbow Icecream Sundae",
		company: "good land brewing co",
		abv: 6,
	},
	{
		id: 7,
		section: 1,
		flavour: "Cream Ale",
		name: "Scoop, There It Is",
		company: "jetty road brewery",
		abv: 5,
	},
	{
		id: 8,
		section: 1,
		flavour: "Sour - Mixed Fermentation",
		name: "High Stakes Bramble",
		company: "slow lane brewing",
		abv: 6,
	},
	{
		id: 9,
		section: 1,
		flavour: "Brown Ale - Australian",
		name: "A rose in every cheek",
		company: "captain bligh's brewery",
		abv: 5,
	},
	{
		id: 10,
		section: 1,
		flavour: "Brown Ale - American",
		name: "Maple Macadamia",
		company: "earth beer company",
		abv: 6.5,
	},
	{
		id: 11,
		section: 1,
		flavour: "Amber/Red - Irish",
		name: "Strawberries and Cream Ale",
		company: "noodledoof",
		abv: 5,
	},
	{
		id: 12,
		section: 1,
		flavour: "Gruit",
		name: "Felonious",
		company: "dollar bill brewing",
		abv: 8.6,
	},
	{
		id: 13,
		section: 1,
		flavour: "Specialty Beer",
		name: "Power Chill",
		company: "akasha brewing co",
		abv: 8.4,
	},
	{
		id: 14,
		section: 1,
		flavour: "Tropical sour ale",
		name: "Colada Royale",
		company: "gypsy fox brewing co",
		abv: 6,
	},
	{
		id: 15,
		section: 1,
		flavour: "IPA - Imperial",
		name: "Mr Grapefruzu",
		company: "cavalier brewing",
		abv: 8,
	},
	{
		id: 16,
		section: 1,
		flavour: "Rauchbier",
		name: "Helles Marzen",
		company: "schlenkerla",
		abv: 5.1,
	},
	{
		id: 17,
		section: 1,
		flavour: "Lager - Festbier/Marzen",
		name: "Winterfest",
		company: "weihenstephan",
		abv: 5.8,
	},
	{
		id: 18,
		section: 1,
		flavour: "Witbier",
		name: "Dream-Vette",
		company: "valley hops brewing",
		abv: 4.9,
	},
	{
		id: 19,
		section: 1,
		flavour: "Ginger/Spiced Beer",
		name: "Red Sky at Morning",
		company: "ramblers ale works",
		abv: 6,
	},
	{
		id: 20,
		section: 1,
		flavour: "IPA - New England",
		name: "Beer For The Burbs",
		company: "thirty eight o six brewing",
		abv: 6.2,
	},
	{
		id: 21,
		section: 2,
		flavour: "Stout - Imperial",
		name: "CHCHCH Cheery Cola",
		company: "Blackflag Brewing",
		abv: 11,
	},
	{
		id: 22,
		section: 2,
		flavour: "Saison/Farmhouse Ale",
		name: "Sunlight Feels Like Bee Stings",
		company: "Urban Alley Brewery",
		abv: 5.5,
	},
	{
		id: 23,
		section: 2,
		flavour: "Specialty Beer",
		name: "S(pud)Mashable",
		company: "Bucket Brewery",
		abv: 5,
	},
	{
		id: 24,
		section: 2,
		flavour: "IPA - New England",
		name: "Yo-Ho-Ho Haze",
		company: "MERINO BREWERY",
		abv: 6.8,
	},
	{
		id: 25,
		section: 2,
		flavour: "Stout - Sweet Stout",
		name: "Double Shelly’s",
		company: "The Coastal Brewing Company Pty Ltd",
		abv: 8,
	},
	{
		id: 26,
		section: 2,
		flavour: "Lager - Festbier/Marzen",
		name: "Vegan Custard Tart",
		company: "Molly Rose Brewing",
		abv: 5.4,
	},
	{
		id: 27,
		section: 2,
		flavour: "Pale Ale - Australian",
		name: "Awesome Blossoms",
		company: "Inner North Brewing Co",
		abv: 5.5,
	},
	{
		id: 28,
		section: 2,
		flavour: "Sour - Kettle Sour",
		name: "Kaijuzám Djinn",
		company: "KAIJU! Beer",
		abv: 6,
	},
	{
		id: 29,
		section: 2,
		flavour: "Fruity Sour",
		name: "Calamansi Berry Bliss Bomb",
		company: "BOATROCKER BREWERS & DISTILLERS",
		abv: 3.8,
	},
	{
		id: 30,
		section: 2,
		flavour: "Specialty Beer",
		name: "Crème Brew-Leè",
		company: "Clifton Hill Brewing",
		abv: 6,
	},
	{
		id: 31,
		section: 2,
		flavour: "Fruit Beer",
		name: "Wild Ferment Cherry Choc Brown",
		company: "Funk Drinks Co",
		abv: 4.2,
	},
	{
		id: 32,
		section: 2,
		flavour: "Sour - Pastry",
		name: "Peach Cobbler Ice Cream",
		company: "The Zythologist",
		abv: 6.4,
	},
	{
		id: 33,
		section: 2,
		flavour: "IPA - Black",
		name: "Dark Bay",
		company: "Scarborough Harbour Brewing Co",
		abv: 7,
	},
	{
		id: 34,
		section: 2,
		flavour: "Baltic Porter",
		name: "The Gloaming 2025",
		company: "BADLANDS BREWERY",
		abv: 7.2,
	},
	{
		id: 35,
		section: 2,
		flavour: "Hazy IPA",
		name: "Mexican Spicy Hazy IPA",
		company: "Frenchies Brewery",
		abv: 6.5,
	},
	{
		id: 36,
		section: 2,
		flavour: "IPA - Red",
		name: "Blood Red Redemption",
		company: "Local Brewing Co",
		abv: 8,
	},
	{
		id: 37,
		section: 2,
		flavour: "Sour",
		name: "Flamen Mods Cough Syrup Sour",
		company: "Reckless Brewing Co",
		abv: 7,
	},
	{
		id: 38,
		section: 2,
		flavour: "IPA - American",
		name: "1960 Whirlpool",
		company: "Blackman's Brewery",
		abv: 6.5,
	},
	{
		id: 39,
		section: 2,
		flavour: "Lager - Dark",
		name: "Tango in the Night",
		company: "Beereratne Brewing",
		abv: 6.2,
	},
	{
		id: 40,
		section: 2,
		flavour: "Red Ale with Nitro",
		name: "Nitro Cherry Bomb",
		company: "Stomping Ground Brewing Co",
		abv: 5.3,
	},
	{
		id: 41,
		section: 3,
		flavour: "IPA - Red",
		name: "Sailors Delight",
		company: "Shelter Brewing Co.",
		abv: 6.1,
	},
	{
		id: 42,
		section: 3,
		flavour: "Sour - Kettle Sour",
		name: "Warbling Warhead",
		company: "Bowden Brewing",
		abv: 5.3,
	},
	{
		id: 43,
		section: 3,
		flavour: "Stout - Sweet Stout",
		name: "Honeycomb Mocha Stout",
		company: "Green Beacon Brewing Co.",
		abv: 5.5,
	},
	{
		id: 44,
		section: 3,
		flavour: "Rauchbier",
		name: "Helles Marzen",
		company: "Schlenkerla",
		abv: 5.1,
	},
	{
		id: 45,
		section: 3,
		flavour: "Lager - Festbier/Marzen",
		name: "Winterfest",
		company: "Weihenstephan",
		abv: 5.8,
	},
	{
		id: 46,
		section: 3,
		flavour: "Hazy IPA",
		name: "Soul Contract",
		company: "Garage Project",
		abv: 6.3,
	},
	{
		id: 47,
		section: 3,
		flavour: "Fruit Beer",
		name: "Hepburn’s Kriek",
		company: "Hepburn Springs Brewing Co",
		abv: 7,
	},
	{
		id: 48,
		section: 3,
		flavour: "Grodziskie/Gräzer",
		name: "Fair Dym-kum",
		company: "JKB Brewing",
		abv: 3.6,
	},
	{
		id: 49,
		section: 3,
		flavour: "Pale Ale - Australian",
		name: "Forrest Aussie Pale",
		company: "Forrest Brewing Company",
		abv: 4.8,
	},
	{
		id: 50,
		section: 3,
		flavour: "IPA - New England",
		name: "Pina Colada",
		company: "7th Day Brewery",
		abv: 6.5,
	},
	{
		id: 51,
		section: 3,
		flavour: "American Strong Ale",
		name: "Wilson",
		company: "Mountain Goat Beer",
		abv: 9.5,
	},
	{
		id: 52,
		section: 3,
		flavour: "IPA - Hazy",
		name: "Horse Shoe Crab Goo",
		company: "Bondi Brewing Co",
		abv: 7,
	},
	{
		id: 53,
		section: 3,
		flavour: "Smoked IPA w/ Terpenes",
		name: "Louie in the Sky with Terpenes",
		company: "King Tide Brewing",
		abv: 7,
	},
	{
		id: 54,
		section: 3,
		flavour: "Sour",
		name: "Imperial Vanilla Cola Sour",
		company: "Moorebeer Brewing Co",
		abv: 6.6,
	},
	{
		id: 55,
		section: 3,
		flavour: "Lager - Imperial Pils/Lager",
		name: "Cool Ship Series",
		company: "Steam Jacket Brewing",
		abv: 7.2,
	},
	{
		id: 56,
		section: 3,
		flavour: "Lager - Australian Pilsner",
		name: "The Stablehand",
		company: "St Andrew's Beach Brewery",
		abv: 5,
	},
	{
		id: 57,
		section: 3,
		flavour: "IPA - American",
		name: "Punching Cones",
		company: "Ballistic Beer Co",
		abv: 6.5,
	},
	{
		id: 58,
		section: 3,
		flavour: "Stout",
		name: "Colombian Coffee Porter",
		company: "Latin Beer",
		abv: 5.9,
	},
	{
		id: 59,
		section: 3,
		flavour: "Dark Mild",
		name: "Oak Aged Dark Mild",
		company: "Straddie Brewing Co.",
		abv: 2.6,
	},
	{
		id: 60,
		section: 3,
		flavour: "Specialty Beer",
		name: "Big Bounty",
		company: "Seeker Brewing",
		abv: 16,
	},
	{
		id: 61,
		section: 4,
		flavour: "IPA - Cold",
		name: "Secret Krush",
		company: "WARRANDYTE BREWING CO.",
		abv: 7,
	},
	{
		id: 62,
		section: 4,
		flavour: "IPA - Sour",
		name: "Crust Cutter",
		company: "Tallboy & Moose",
		abv: 8,
	},
	{
		id: 63,
		section: 4,
		flavour: "IPA - American",
		name: "Coming to America",
		company: "Prickly pete and the wolf brewing co",
		abv: 7,
	},
	{
		id: 64,
		section: 4,
		flavour: "Belgian Blond Ale",
		name: "BlondeSoy",
		company: "TwoBays Brewing Co",
		abv: 6.4,
	},
	{
		id: 65,
		section: 4,
		flavour: "Specialty Beer",
		name: "Banana Chocolate Cake Ale",
		company: "3 Griffins Brewing",
		abv: 4.8,
	},
	{
		id: 66,
		section: 4,
		flavour: "Sour - Gose",
		name: "Pickle My Fancy",
		company: "Stoic Brewing",
		abv: 4,
	},
	{
		id: 67,
		section: 4,
		flavour: "IPA - Hazy",
		name: "Princess Peach",
		company: "Dangerous Ales",
		abv: 10,
	},
	{
		id: 68,
		section: 4,
		flavour: "Cream Ale",
		name: "Luwak Latte",
		company: "Hound & Stag Brewing Co",
		abv: 7.5,
	},
	{
		id: 69,
		section: 4,
		flavour: "Stout - Oatmeal",
		name: "Broken Bay Pearl",
		company: "Six String Brewing Co",
		abv: 7,
	},
	{
		id: 70,
		section: 4,
		flavour: "IPA - Imperial",
		name: "Big Buckler",
		company: "Curly Lewis Brewery",
		abv: 10.5,
	},
	{
		id: 71,
		section: 4,
		flavour: "Stout - Pastry",
		name: "Milky Bar Imperial White Stout",
		company: "Your Mates Brewing",
		abv: 8,
	},
	{
		id: 72,
		section: 4,
		flavour: "Sour - Kettle Sour",
		name: "Green Ant & Emu",
		company: "Jarrah Boy",
		abv: 4.5,
	},
	{
		id: 73,
		section: 4,
		flavour: "Lager - Australian Pilsner",
		name: "Citrus and Sea",
		company: "Seven Mile Brewing Co",
		abv: 4.9,
	},
	{
		id: 74,
		section: 4,
		flavour: "Specialty Beer",
		name: "Lemon Curd",
		company: "Sauce Brewing Co",
		abv: 6.5,
	},
	{
		id: 75,
		section: 4,
		flavour: "IPA - New England (Double)",
		name: "Daylight Robbery",
		company: "Meletos Brewing",
		abv: 8,
	},
	{
		id: 76,
		section: 4,
		flavour: "Rauchbier",
		name: "Helles Marzen",
		company: "Schlenkerla",
		abv: 5.1,
	},
	{
		id: 77,
		section: 4,
		flavour: "Lager - Festbier/Marzen",
		name: "Winterfest",
		company: "Weihenstephan",
		abv: 5.8,
	},
	{
		id: 78,
		section: 4,
		flavour: "Fuggle IPA",
		name: "Angry Miner",
		company: "Bendigo Brewing",
		abv: 6.5,
	},
	{
		id: 79,
		section: 4,
		flavour: "Other - Fruit Enhanced Hazy",
		name: "Jumbo Juice",
		company: "Mountain Culture Beer Co",
		abv: 8,
	},
	{
		id: 80,
		section: 4,
		flavour: "Kölsch",
		name: "Snowy`s Bitter",
		company: "SNOWYS BREWERY",
		abv: 4.9,
	},
	{
		id: 81,
		section: 5,
		flavour: "Specialty Beer",
		name: "Passionfruit and Blood Orange Witbier",
		company: "Red Dog Brewery",
		abv: 5.2,
	},
	{
		id: 82,
		section: 5,
		flavour: "Specialty Beer",
		name: "Peeling Guilty",
		company: "Copperlode Brewing Company",
		abv: 7,
	},
	{
		id: 83,
		section: 5,
		flavour: "Stout - Imperial",
		name: "Muy Caliente Barrel Aged Stout",
		company: "Moon Dog Brewery",
		abv: 9.9,
	},
	{
		id: 84,
		section: 5,
		flavour: "IPA - Australian",
		name: "Slant Six",
		company: "Ale Mary Brewing Co",
		abv: 6,
	},
	{
		id: 85,
		section: 5,
		flavour: "Stout - Tropical",
		name: "Tapache",
		company: "Alice Springs Brewing Co",
		abv: 4.5,
	},
	{
		id: 86,
		section: 5,
		flavour: "IPA - Red",
		name: "Fields of Red",
		company: "Hop Hen Brewing",
		abv: 7.5,
	},
	{
		id: 87,
		section: 5,
		flavour: "Rauchbier",
		name: "Brisket Burnt Ends Rauchbier",
		company: "Moffat Beach Brewing Co",
		abv: 6,
	},
	{
		id: 88,
		section: 5,
		flavour: "IPA - Hazy",
		name: "Rock Jock",
		company: "2 Sherpas Brewing Company Pty Ltd",
		abv: 6.5,
	},
	{
		id: 89,
		section: 5,
		flavour: "IPA - American",
		name: "WTDHWCIIIPA",
		company: "Devilbend Farm Beer Co.",
		abv: 9,
	},
	{
		id: 90,
		section: 5,
		flavour: "Sour - Gose",
		name: "Cucumber Lychee Gose",
		company: "Mountain Monk Brewers",
		abv: 4.5,
	},
	{
		id: 91,
		section: 5,
		flavour: "Lager - Australian",
		name: "Bright-Eyed Lager",
		company: "Earlybird",
		abv: 0.5,
	},
	{
		id: 92,
		section: 5,
		flavour: "Porter",
		name: "Veez Nutz",
		company: "The Social Brewers",
		abv: 5.1,
	},
	{
		id: 93,
		section: 5,
		flavour: "Stout - Sweet Stout",
		name: "Bench",
		company: "Braeside Brewing Company",
		abv: 5.8,
	},
	{
		id: 94,
		section: 5,
		flavour: "Saison/Farmhouse Ale",
		name: "F you I wont do what you tell me",
		company: "Green Gully Brewing & Island Beer",
		abv: 5,
	},
	{
		id: 95,
		section: 5,
		flavour: "Weizen/Weissbier/Hefeweizen",
		name: "Banana Slamma",
		company: "Impi Brewers",
		abv: 4.6,
	},
	{
		id: 96,
		section: 5,
		flavour: "Apple Pie Graf",
		name: "Apple-Y-Ever After",
		company: "Capital Brewing and Batlow Cider Collab",
		abv: 8.5,
	},
	{
		id: 97,
		section: 5,
		flavour: "IPA - Black",
		name: "Dark Matter",
		company: "PSYCHO SUZIE’S BREWING",
		abv: 7,
	},
	{
		id: 98,
		section: 5,
		flavour: "Hybrid Mead",
		name: "Honey, where did Candy go?",
		company: "Surfers Paradise Brewing Co",
		abv: 8,
	},
	{
		id: 99,
		section: 5,
		flavour: "Lager - Australian Pilsner",
		name: "Ginger Pineapple Sour",
		company: "Broulee Brewhouse",
		abv: 4.2,
	},
	{
		id: 100,
		section: 5,
		flavour: "Stout - Pastry",
		name: "Dawn’s Sweet Embrace",
		company: "Westside Ale Works",
		abv: 9.5,
	},
	{
		id: 101,
		section: 6,
		flavour: "Sour",
		name: "Gingerbread Pastry",
		company: "Shout Brewing Co",
		abv: 6,
	},
	{
		id: 102,
		section: 6,
		flavour: "Brown Ale - UK",
		name: "Brownie Bomb",
		company: "Wolf of the Willows",
		abv: 5.5,
	},
	{
		id: 103,
		section: 6,
		flavour: "Lager - Hoppy",
		name: "Seeds Flowers Leaves",
		company: "Precinct Brewing",
		abv: 6,
	},
	{
		id: 104,
		section: 6,
		flavour: "Rauchbier",
		name: "Helles Marzen",
		company: "Schlenkerla",
		abv: 5.1,
	},
	{
		id: 105,
		section: 6,
		flavour: "Lager - Festbier/Marzen",
		name: "Winterfest",
		company: "Weihenstephan",
		abv: 5.8,
	},
	{
		id: 106,
		section: 6,
		flavour: "Fuggle IPA",
		name: "Angry Miner",
		company: "Bendigo Brewing",
		abv: 6.5,
	},
	{
		id: 107,
		section: 6,
		flavour: "Ale",
		name: "Golden Tears and Red Ale",
		company: "Amber Brewing",
		abv: 5,
	},
	{
		id: 108,
		section: 6,
		flavour: "Pale Ale",
		name: "Rubia",
		company: "Miguel Maestre",
		abv: 4.2,
	},
	{
		id: 109,
		section: 6,
		flavour: "Traditional Perry",
		name: "Eddies Smooth Pear",
		company: "Eddie's Cider",
		abv: 3.8,
	},
	{
		id: 110,
		section: 6,
		flavour: "Cider with Fruit",
		name: "Cidermakers Select Classic Dry",
		company: "SPREYTON CIDER CO",
		abv: 6.5,
	},
	{
		id: 111,
		section: 6,
		flavour: "Spirit forward",
		name: "Mango Margarita",
		company: "Casa Spirits & Cocktails",
		abv: 8,
	},
	{
		id: 112,
		section: 6,
		flavour: "Specialty Cider",
		name: "Toddy",
		company: "Flying Brick Cider Co",
		abv: 7.5,
	},
	{
		id: 113,
		section: 6,
		flavour: "Cocktail",
		name: "Tropical Storm",
		company: "Matso's Brewery",
		abv: 6,
	},
	{
		id: 114,
		section: 6,
		flavour: "Cocktail",
		name: "Ginger Monkey",
		company: "Monkey Shoulder",
		abv: 5.2,
	},
	{
		id: 115,
		section: 6,
		flavour: "Goser",
		name: "The Barry Raspberry Crush",
		company: "Barrys",
		abv: 4.2,
	},
	{
		id: 116,
		section: 6,
		flavour: "Seltzer",
		name: "Crusher – Hard Creaming Soda",
		company: "Dad & Dave's Brewing",
		abv: 4.5,
	},
	{
		id: 117,
		section: 6,
		flavour: "Spritzes",
		name: "Aperatito",
		company: "2 Halfs Brewing Distilling #2",
		abv: 9,
	},
	{
		id: 118,
		section: 6,
		flavour: "Spritzes",
		name: "Lemon Desert Lime Iced Tea",
		company: "Ventura Brewing",
		abv: 6,
	},
];

export const BEER_SECTIONS: number[] = [];
BEERS.forEach((beer) => {
	if (BEER_SECTIONS.includes(beer.section)) return;

	BEER_SECTIONS.push(beer.section);
});
